name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.5
          terraform_wrapper: false

      - name: Lint agents
        run: ./scripts/lint-agents.sh

      - name: Lint Terraform templates
        run: ./scripts/lint-terraform.sh

      - name: Generate integrations
        run: ./scripts/convert.sh
